import Head from 'next/head';
import { Footer, Navbar } from '../components';
import GlobalStyle from '../styles/globalstyles.js';

const Layout = ({ children }) => {
	return (
		<>
			<Head>
				<title>Cool Tech Design | Web Development Agency</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<meta name='viewport' content='width=device-width, initial-scale=1.0' />
				<meta httpEquiv='Content-Type' content='text/html;charset=UTF-8' />
				<meta
					name='description'
					content='Cool Tech Design is one of the best web development agency in india. We provide modern, professional and lead generation website design and development. '
				/>
				<meta
					name='keywords'
					content='cool tech design, cooltechdesign, web development agency, web development, website development, web developer in banglore, website design, seo, ecommerce development, corporate website development, software development'
				/>
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link
					rel='preconnect'
					href='https://fonts.gstatic.com'
					crossOrigin='true'
				/>
			</Head>

			<Navbar />
			<main>{children}</main>
			<Footer />
			<GlobalStyle />
		</>
	);
};

export default Layout;
